# Todas as recorrencias de "Volumes:..." devem ser descomentadas ao ir para producao

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432" # Porta do host (5433) para a porta do container (5432)
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    
  spring-app:
    image: backend-sinaleasy:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_URL}"]
      interval: 10s
      retries: 5
    container_name: spring-app
    build:
      context: ./sinaleasy-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres-db
    
  angular-app:
    image: frontend-sinaleasy:latest
    build:
      context: ./sinaleasy-front
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Porta do host (4200) pra porta padrão do Nginx no container
    depends_on:
      - spring-app

# volumes:
#   postgres-data:
