# Todas as recorrencias de "Volumes:..." devem ser descomentadas ao ir para producao
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432" # Porta do host (5433) para a porta do container (5432)
    environment:
      - POSTGRES_DB=sinaleasy
      - POSTGRES_USER=sinaleasy-db_owner
      - POSTGRES_PASSWORD=INSERIR_SENHA_PROVEDOR_BANCO
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    
  spring-app:
    image: backend-sinaleasy:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sinaleasy-db_owner", "-d", "sinaleasy"]
      interval: 10s
      retries: 5
    container_name: spring-app
    build:
      context: ./sinaleasy-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/sinaleasy
      SPRING_DATASOURCE_USERNAME: sinaleasy-db_owner
      SPRING_DATASOURCE_PASSWORD: INSERIR_SENHA_PROVEDOR
    depends_on:
      - postgres-db
    
  angular-app:
    build:
      context: ./sinaleasy-front
      dockerfile: Dockerfile
      container_name: angular-app
    ports:
      - "4200:80" # Porta do host (4200) pra porta padrao do Nginx no container
    depends_on:
      - spring-app

# volumes:
#   postgres-data: