# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: my-image-name

#     steps:
#     - uses: actions/checkout@v4

#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
    
#     - name: Log in to Docker Hub
#       if: github.event_name == 'push'
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#     - name: Push Docker image
#       if: github.event_name == 'push'
#       run: docker push ${{ env.IMAGE_NAME }}:$(date +%s)
